name: zentime
description: A zen time tracking app for multi-project management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Audio
  audioplayers: ^6.1.0
  
  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0
  
  # Utils
  uuid: ^3.0.7
  
  # Overlay & System Tray (Desktop only)
  desktop_window: ^0.4.0
  system_tray: ^2.0.3
  window_manager: ^0.4.2
  hotkey_manager: ^0.2.3  # NEW!


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  hotkey_manager: ^0.2.3  # NEW!


flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/