import 'package:hive/hive.dart';

part 'calorie_entry.g.dart';

@HiveType(typeId: 5)
class CalorieEntry extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String foodName;

  // Total calories (already multiplied by qty)
  @HiveField(2)
  int calories;

  @HiveField(3)
  DateTime date;

  // qty: how many portions — stored for display in log
  // HiveField(4) — default 1 for backward compat (old entries without this field)
  @HiveField(4, defaultValue: 1)
  int quantity;

  CalorieEntry({
    required this.id,
    required this.foodName,
    required this.calories,
    required this.date,
    this.quantity = 1,
  });
}

@HiveType(typeId: 6)
class CalorieGoal extends HiveObject {
  @HiveField(0)
  int dailyTargetKcal;

  CalorieGoal({this.dailyTargetKcal = 1500});
}

// ── Preset food list ─────────────────────────────────────────
class FoodPreset {
  final String name;
  final int calories;
  const FoodPreset({required this.name, required this.calories});
}

const List<FoodPreset> kFoodPresets = [
  FoodPreset(name: 'Kopi tanpa gula + krimer 4 g', calories: 20),
  FoodPreset(name: 'Nasi 1 sdm', calories: 25),
  FoodPreset(name: 'Malkist gula kecil 1 keping', calories: 35),
  FoodPreset(name: 'Telur rebus 1 butir', calories: 70),
  FoodPreset(name: 'Tempe goreng 1 potong', calories: 110),
  FoodPreset(name: 'Telur ceplok 1 butir', calories: 110),
  FoodPreset(name: 'Tahu bakso 1 buah', calories: 80),
  FoodPreset(name: 'Ayam bakar 1 potong', calories: 250),
  FoodPreset(name: 'Mentega 1 sdt', calories: 35),
  FoodPreset(name: 'Roti tawar 1 lembar', calories: 70),
  FoodPreset(name: 'Sambal 1 sdm', calories: 20),
  FoodPreset(name: 'Indomie rebus + telur 1 porsi', calories: 460),
  FoodPreset(name: 'Kue jajanan pasar 1 buah', calories: 150),
  FoodPreset(name: 'Kurma 1 butir', calories: 25),
  FoodPreset(name: 'Nasi goreng 1 sdm', calories: 40),
  FoodPreset(name: 'Kremes 1 sdm', calories: 30),
  FoodPreset(name: 'Ayam goreng 1 potong', calories: 260),
  FoodPreset(name: 'Ayam goreng tepung dada 1 potong', calories: 320),
  FoodPreset(name: 'Ayam goreng tepung sayap 1 potong', calories: 180),
  FoodPreset(name: 'Meses 1 sdm', calories: 50),
  FoodPreset(name: 'Roti pisang keju 1 buah', calories: 280),
  FoodPreset(name: 'Ayam lada hitam 1 sdm', calories: 40),
  FoodPreset(name: 'Buah pisang 1 buah', calories: 100),
  FoodPreset(name: 'Es krim 1 scoop', calories: 130),
  FoodPreset(name: 'Es teh manis 1 gelas', calories: 90),
  FoodPreset(name: 'Indomie goreng jumbo 1 porsi', calories: 550),
  FoodPreset(name: 'Nasi Padang 1 porsi nasi', calories: 350),
  FoodPreset(name: 'Ayam suwir 1 sdm', calories: 40),
  FoodPreset(name: 'Es kopi susu 1 gelas', calories: 200),
  FoodPreset(name: 'Rawon 1 mangkuk', calories: 350),
  FoodPreset(name: 'Rendang 1 potong', calories: 90),
  FoodPreset(name: 'Roti bakar mentega gula 2 potong', calories: 240),
  FoodPreset(name: 'Roti bakar keju 1 porsi', calories: 280),
  FoodPreset(name: 'Roti bakar meses 1 porsi', calories: 250),
  FoodPreset(name: 'Sayur berkuah 1 porsi', calories: 75),
  FoodPreset(name: 'Selai coklat 1 sdm', calories: 40),
  FoodPreset(name: 'Serundeng + daging 1 potong', calories: 110),
  FoodPreset(name: 'Siomay 1 porsi kecil', calories: 280),
  FoodPreset(name: 'Sop ayam 1 mangkuk', calories: 200),
  FoodPreset(name: 'Sosis ayam 1 buah', calories: 120),
  FoodPreset(name: 'Sosis isi keju 1 buah', calories: 120),
  FoodPreset(name: 'Kerupuk udang 1 buah', calories: 30),
  FoodPreset(name: 'Kerupuk putih 1 buah', calories: 35),
  FoodPreset(name: 'Semangka 1 potong', calories: 50),
  FoodPreset(name: 'Bakwan sayur 1 buah', calories: 130),
  FoodPreset(name: 'Batagor 1 porsi', calories: 300),
  FoodPreset(name: 'Bihun goreng 1 sdm', calories: 22),
  FoodPreset(name: 'Capcay 1 sdm', calories: 12),
  FoodPreset(name: 'Daging lada hitam 1 sdm', calories: 50),
  FoodPreset(name: 'Dimsum 1 buah', calories: 50),
  FoodPreset(name: 'Ketan saus duren 1 porsi', calories: 300),
  FoodPreset(name: 'Kue nastar 1 buah', calories: 70),
  FoodPreset(name: 'Mangga 1 buah', calories: 150),
  FoodPreset(name: 'Nasi goreng 1 porsi', calories: 600),
  FoodPreset(name: 'Patty daging 1 buah', calories: 200),
  FoodPreset(name: 'Sapo tahu 1 sdm', calories: 18),
  FoodPreset(name: 'Tempe goreng tepung 1 buah', calories: 120),
  FoodPreset(name: 'Burger ayam 1 buah', calories: 350),
  FoodPreset(name: 'Burger daging 1 buah', calories: 450),
  FoodPreset(name: 'Kebab 1 porsi', calories: 400),
  FoodPreset(name: 'Tongseng 1 mangkuk', calories: 400),
  FoodPreset(name: 'Roti coklat 1 buah', calories: 220),
  FoodPreset(name: 'Roti keju 1 buah', calories: 220),
  FoodPreset(name: 'Roti sobek 1 potong', calories: 90),
  FoodPreset(name: 'Soto ayam 1 mangkuk', calories: 250),
  FoodPreset(name: 'Soto daging 1 mangkuk', calories: 300),
  FoodPreset(name: 'Sus krim 1 buah', calories: 180),
  FoodPreset(name: 'Tempe bacem 1 potong', calories: 120),
  FoodPreset(name: 'Tempe orek 1 sdm', calories: 60),
  FoodPreset(name: 'Tahu goreng tepung 1 buah', calories: 100),
  FoodPreset(name: 'Sayur tumis 1 porsi', calories: 75),
  FoodPreset(name: 'Kastengel 1 butir', calories: 30),
  FoodPreset(name: 'Sumpia 1 buah', calories: 30),
  FoodPreset(name: 'Anggur 5 butir', calories: 35),
  FoodPreset(name: 'Apel 1 potong', calories: 20),
  FoodPreset(name: 'Cilok 1 buah', calories: 40),
  FoodPreset(name: 'Cireng 1 buah', calories: 80),
  FoodPreset(name: 'Es kelapa muda tanpa gula 1 gelas', calories: 60),
  FoodPreset(name: 'Gula 1 sdm', calories: 45),
  FoodPreset(name: 'Gula 1 sdt', calories: 16),
  FoodPreset(name: 'Jeruk 1 buah', calories: 60),
  FoodPreset(name: 'Kacang goreng 1 genggam', calories: 180),
  FoodPreset(name: 'Kacang tepung 1 genggam', calories: 200),
  FoodPreset(name: 'Kentang goreng 5 potong', calories: 50),
  FoodPreset(name: 'Kornet 1 sdm', calories: 50),
  FoodPreset(name: 'Martabak coklat keju 1 potong', calories: 320),
  FoodPreset(name: 'Martabak keju 1 potong', calories: 180),
  FoodPreset(name: 'Pastel 1 buah', calories: 220),
  FoodPreset(name: 'Bihun goreng 1 porsi', calories: 400),
  FoodPreset(name: 'Sate kambing 1 tusuk', calories: 80),
  FoodPreset(name: 'Sate ayam 1 tusuk', calories: 60),
  FoodPreset(name: 'Susu kental manis 1 sdm', calories: 60),
  FoodPreset(name: 'Susu UHT 200 ml', calories: 130),
  FoodPreset(name: 'Tahu goreng 1 potong', calories: 90),
  FoodPreset(name: 'Tahu gulai 1 potong', calories: 80),
  FoodPreset(name: 'Tumis buncis 1 porsi', calories: 120),
  FoodPreset(name: 'Tumis kangkung 1 porsi', calories: 100),
  FoodPreset(name: 'Tumis tempe 1 porsi', calories: 180),
  FoodPreset(name: 'Udang goreng 1 porsi', calories: 280),
  FoodPreset(name: 'Gudeg 1 porsi', calories: 350),
  FoodPreset(name: 'Krecek 1 sdm', calories: 40),
  FoodPreset(name: 'Sayur sop 1 mangkuk', calories: 100),
  FoodPreset(name: 'Combro 1 buah', calories: 200),
  FoodPreset(name: 'Risol 1 buah', calories: 180),
  FoodPreset(name: 'Ikan bakar 1 potong', calories: 200),
  FoodPreset(name: 'Jus alpukat 1 gelas', calories: 300),
  FoodPreset(name: 'Jus mangga 1 gelas', calories: 150),
  FoodPreset(name: 'Kue pasar campur 1 porsi', calories: 400),
  FoodPreset(name: 'Croissant 1 buah', calories: 260),
  FoodPreset(name: 'Es jeruk 1 gelas', calories: 120),
  FoodPreset(name: 'Kue putri salju 1 buah', calories: 60),
  FoodPreset(name: 'Pukis 1 buah', calories: 150),
  FoodPreset(name: 'Roti sobek isi coklat 1 potong', calories: 120),
  FoodPreset(name: 'Telur dadar 1 butir', calories: 120),
  FoodPreset(name: 'Tahu kriuk 1 buah', calories: 50),
  FoodPreset(name: 'Pudding 1 cup', calories: 160),
  FoodPreset(name: 'Popcorn 1 mangkuk', calories: 150),
  FoodPreset(name: 'Nugget ayam 1 buah', calories: 80),
  FoodPreset(name: 'Onigiri 1 buah', calories: 200),
  FoodPreset(name: 'Pizza slice 1 potong', calories: 280),
  FoodPreset(name: 'Tumis tahu 1 porsi', calories: 150),
  FoodPreset(name: 'Wingko babat 1 potong', calories: 200),
  FoodPreset(name: 'Ayam balado 1 potong', calories: 260),
  FoodPreset(name: 'Ayam kecap 1 potong', calories: 240),
  FoodPreset(name: 'Ayam opor 1 potong', calories: 220),
  FoodPreset(name: 'Bebek bakar 1 potong', calories: 320),
  FoodPreset(name: 'Bebek goreng 1 potong', calories: 350),
  FoodPreset(name: 'Bika Ambon 1 potong', calories: 150),
  FoodPreset(name: 'Bolu kukus 1 buah', calories: 150),
  FoodPreset(name: 'Brownies 1 potong', calories: 220),
  FoodPreset(name: 'Brownies mini 1 potong', calories: 120),
  FoodPreset(name: 'Bubur ayam 1 mangkuk', calories: 300),
  FoodPreset(name: 'Cake 1 potong', calories: 320),
  FoodPreset(name: 'Capcay 1 porsi', calories: 180),
  FoodPreset(name: 'Cheesecake 1 potong', calories: 300),
  FoodPreset(name: 'Cimol 1 buah', calories: 50),
  FoodPreset(name: 'Cumi goreng 1 porsi', calories: 300),
  FoodPreset(name: 'Dodol 1 potong kecil', calories: 150),
  FoodPreset(name: 'Donat 1 buah', calories: 230),
  FoodPreset(name: 'Es krim cone 1 buah', calories: 180),
  FoodPreset(name: 'Es krim stik 1 buah', calories: 120),
  FoodPreset(name: 'Gulai kambing 1 porsi', calories: 250),
  FoodPreset(name: 'Hot dog 1 buah', calories: 320),
  FoodPreset(name: 'Indomie goreng 1 bungkus', calories: 400),
  FoodPreset(name: 'Indomie rebus 1 bungkus', calories: 380),
  FoodPreset(name: 'Jenang 1 potong', calories: 180),
  FoodPreset(name: 'Kacang pilus 1 genggam', calories: 150),
  FoodPreset(name: 'Keripik kentang 5 potong', calories: 40),
  FoodPreset(name: 'Keripik 5 potong', calories: 40),
  FoodPreset(name: 'Keju slice 1 lembar', calories: 60),
  FoodPreset(name: 'Keju parut 1 sdm', calories: 25),
  FoodPreset(name: 'Ketupat 1 potong', calories: 60),
  FoodPreset(name: 'Klepon 1 buah', calories: 80),
  FoodPreset(name: 'Kue apem 1 buah', calories: 120),
  FoodPreset(name: 'Kue lapis legit 1 potong kecil', calories: 200),
  FoodPreset(name: 'Kwetiau goreng 1 porsi', calories: 450),
  FoodPreset(name: 'Lele goreng 1 ekor', calories: 220),
  FoodPreset(name: 'Lemper 1 buah', calories: 180),
  FoodPreset(name: 'Lontong 1 potong', calories: 50),
  FoodPreset(name: 'Makaroni schotel', calories: 150),
  FoodPreset(name: 'Melon 1 potong', calories: 50),
  FoodPreset(name: 'Nagasari 1 buah', calories: 120),
  FoodPreset(name: 'Onde-onde 1 buah', calories: 180),
  FoodPreset(name: 'Pepaya 1 potong', calories: 60),
  FoodPreset(name: 'Perkedel kentang 1 buah', calories: 120),
  FoodPreset(name: 'Peyek kacang 1 buah', calories: 80),
  FoodPreset(name: 'Pisang goreng 1 buah', calories: 90),
  FoodPreset(name: 'Pukis mini 1 buah', calories: 80),
  FoodPreset(name: 'Roti abon 1 buah', calories: 300),
  FoodPreset(name: 'Roti sobek isi keju 1 potong', calories: 130),
  FoodPreset(name: 'Roti sobek isi susu 1 potong', calories: 120),
  FoodPreset(name: 'Roti sosis keju 1 buah', calories: 300),
  FoodPreset(name: 'Saltcheese 1 keping', calories: 20),
  FoodPreset(name: 'Sarden 1 sdm', calories: 40),
  FoodPreset(name: 'Sate padang 1 tusuk', calories: 90),
  FoodPreset(name: 'Sayur asem 1 mangkuk', calories: 80),
  FoodPreset(name: 'Sayur bayam 1 mangkuk', calories: 70),
  FoodPreset(name: 'Sayur lodeh 1 mangkuk', calories: 120),
  FoodPreset(name: 'Serabi 1 buah', calories: 150),
  FoodPreset(name: 'Tahu bacem 1 potong', calories: 90),
  FoodPreset(name: 'Waffle 1 buah', calories: 200),
  FoodPreset(name: 'Waffle coklat 1 buah', calories: 250),
  FoodPreset(name: 'Waffle keju 1 buah', calories: 240),
  FoodPreset(name: 'Wajik 1 potong', calories: 200),
  FoodPreset(name: 'Yogurt 1 cup', calories: 140),
];