name: tes_love
description: Aplikasi tes 5 Love Language dengan quiz 30 pertanyaan.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Local storage
  shared_preferences: ^2.3.2

  # Chart / visualisasi hasil
  fl_chart: ^0.70.2

  # Icon pack tambahan
  iconsax_flutter: ^1.0.0

  # UUID untuk user id unik
  uuid: ^4.5.1

  # Animasi
  flutter_animate: ^4.5.0

  # Google Fonts
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"