name: lisaana_quiz
description: "Arabic vocabulary learning app with quiz and flashcards"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Storage
  shared_preferences: ^2.2.3
  
  # Audio
  audioplayers: ^6.0.0
  
  # UI Components
  google_fonts: ^6.2.1
  
  # Utilities
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"