name: timer_app
description: Minimal floating timer for Windows 11.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  window_manager: ^0.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/ding.mp3