import 'character_item.dart';

/// Seluruh aksara Hiragana standar (gojuon + dakuten/handakuten + yoon),
/// total 104 item. Urutan list ini SENGAJA disusun dari yang paling dasar
/// (vokal tunggal) sampai yang paling kompleks (kombinasi yoon), karena
/// [QuizGeneratorService] menggunakan urutan ini untuk menaikkan kesulitan
/// secara gradual di sepanjang 50 level.
const List<CharacterItem> kHiraganaData = [
  // --- Gojuon dasar (46) ---
  CharacterItem(character: 'あ', romaji: 'a'),
  CharacterItem(character: 'い', romaji: 'i'),
  CharacterItem(character: 'う', romaji: 'u'),
  CharacterItem(character: 'え', romaji: 'e'),
  CharacterItem(character: 'お', romaji: 'o'),
  CharacterItem(character: 'か', romaji: 'ka'),
  CharacterItem(character: 'き', romaji: 'ki'),
  CharacterItem(character: 'く', romaji: 'ku'),
  CharacterItem(character: 'け', romaji: 'ke'),
  CharacterItem(character: 'こ', romaji: 'ko'),
  CharacterItem(character: 'さ', romaji: 'sa'),
  CharacterItem(character: 'し', romaji: 'shi'),
  CharacterItem(character: 'す', romaji: 'su'),
  CharacterItem(character: 'せ', romaji: 'se'),
  CharacterItem(character: 'そ', romaji: 'so'),
  CharacterItem(character: 'た', romaji: 'ta'),
  CharacterItem(character: 'ち', romaji: 'chi'),
  CharacterItem(character: 'つ', romaji: 'tsu'),
  CharacterItem(character: 'て', romaji: 'te'),
  CharacterItem(character: 'と', romaji: 'to'),
  CharacterItem(character: 'な', romaji: 'na'),
  CharacterItem(character: 'に', romaji: 'ni'),
  CharacterItem(character: 'ぬ', romaji: 'nu'),
  CharacterItem(character: 'ね', romaji: 'ne'),
  CharacterItem(character: 'の', romaji: 'no'),
  CharacterItem(character: 'は', romaji: 'ha'),
  CharacterItem(character: 'ひ', romaji: 'hi'),
  CharacterItem(character: 'ふ', romaji: 'fu'),
  CharacterItem(character: 'へ', romaji: 'he'),
  CharacterItem(character: 'ほ', romaji: 'ho'),
  CharacterItem(character: 'ま', romaji: 'ma'),
  CharacterItem(character: 'み', romaji: 'mi'),
  CharacterItem(character: 'む', romaji: 'mu'),
  CharacterItem(character: 'め', romaji: 'me'),
  CharacterItem(character: 'も', romaji: 'mo'),
  CharacterItem(character: 'や', romaji: 'ya'),
  CharacterItem(character: 'ゆ', romaji: 'yu'),
  CharacterItem(character: 'よ', romaji: 'yo'),
  CharacterItem(character: 'ら', romaji: 'ra'),
  CharacterItem(character: 'り', romaji: 'ri'),
  CharacterItem(character: 'る', romaji: 'ru'),
  CharacterItem(character: 'れ', romaji: 're'),
  CharacterItem(character: 'ろ', romaji: 'ro'),
  CharacterItem(character: 'わ', romaji: 'wa'),
  CharacterItem(character: 'を', romaji: 'wo'),
  CharacterItem(character: 'ん', romaji: 'n'),

  // --- Dakuten (20) ---
  CharacterItem(character: 'が', romaji: 'ga'),
  CharacterItem(character: 'ぎ', romaji: 'gi'),
  CharacterItem(character: 'ぐ', romaji: 'gu'),
  CharacterItem(character: 'げ', romaji: 'ge'),
  CharacterItem(character: 'ご', romaji: 'go'),
  CharacterItem(character: 'ざ', romaji: 'za'),
  CharacterItem(character: 'じ', romaji: 'ji'),
  CharacterItem(character: 'ず', romaji: 'zu'),
  CharacterItem(character: 'ぜ', romaji: 'ze'),
  CharacterItem(character: 'ぞ', romaji: 'zo'),
  CharacterItem(character: 'だ', romaji: 'da'),
  CharacterItem(character: 'ぢ', romaji: 'di'),
  CharacterItem(character: 'づ', romaji: 'du'),
  CharacterItem(character: 'で', romaji: 'de'),
  CharacterItem(character: 'ど', romaji: 'do'),
  CharacterItem(character: 'ば', romaji: 'ba'),
  CharacterItem(character: 'び', romaji: 'bi'),
  CharacterItem(character: 'ぶ', romaji: 'bu'),
  CharacterItem(character: 'べ', romaji: 'be'),
  CharacterItem(character: 'ぼ', romaji: 'bo'),

  // --- Handakuten (5) ---
  CharacterItem(character: 'ぱ', romaji: 'pa'),
  CharacterItem(character: 'ぴ', romaji: 'pi'),
  CharacterItem(character: 'ぷ', romaji: 'pu'),
  CharacterItem(character: 'ぺ', romaji: 'pe'),
  CharacterItem(character: 'ぽ', romaji: 'po'),

  // --- Yoon (33) ---
  CharacterItem(character: 'きゃ', romaji: 'kya'),
  CharacterItem(character: 'きゅ', romaji: 'kyu'),
  CharacterItem(character: 'きょ', romaji: 'kyo'),
  CharacterItem(character: 'しゃ', romaji: 'sha'),
  CharacterItem(character: 'しゅ', romaji: 'shu'),
  CharacterItem(character: 'しょ', romaji: 'sho'),
  CharacterItem(character: 'ちゃ', romaji: 'cha'),
  CharacterItem(character: 'ちゅ', romaji: 'chu'),
  CharacterItem(character: 'ちょ', romaji: 'cho'),
  CharacterItem(character: 'にゃ', romaji: 'nya'),
  CharacterItem(character: 'にゅ', romaji: 'nyu'),
  CharacterItem(character: 'にょ', romaji: 'nyo'),
  CharacterItem(character: 'ひゃ', romaji: 'hya'),
  CharacterItem(character: 'ひゅ', romaji: 'hyu'),
  CharacterItem(character: 'ひょ', romaji: 'hyo'),
  CharacterItem(character: 'みゃ', romaji: 'mya'),
  CharacterItem(character: 'みゅ', romaji: 'myu'),
  CharacterItem(character: 'みょ', romaji: 'myo'),
  CharacterItem(character: 'りゃ', romaji: 'rya'),
  CharacterItem(character: 'りゅ', romaji: 'ryu'),
  CharacterItem(character: 'りょ', romaji: 'ryo'),
  CharacterItem(character: 'ぎゃ', romaji: 'gya'),
  CharacterItem(character: 'ぎゅ', romaji: 'gyu'),
  CharacterItem(character: 'ぎょ', romaji: 'gyo'),
  CharacterItem(character: 'じゃ', romaji: 'ja'),
  CharacterItem(character: 'じゅ', romaji: 'ju'),
  CharacterItem(character: 'じょ', romaji: 'jo'),
  CharacterItem(character: 'びゃ', romaji: 'bya'),
  CharacterItem(character: 'びゅ', romaji: 'byu'),
  CharacterItem(character: 'びょ', romaji: 'byo'),
  CharacterItem(character: 'ぴゃ', romaji: 'pya'),
  CharacterItem(character: 'ぴゅ', romaji: 'pyu'),
  CharacterItem(character: 'ぴょ', romaji: 'pyo'),
];
