import 'character_item.dart';

/// Seluruh aksara Katakana standar (gojuon + dakuten/handakuten + yoon),
/// total 104 item, dengan urutan kesulitan yang sama persis dengan
/// [kHiraganaData] agar progres belajar antar kategori konsisten.
const List<CharacterItem> kKatakanaData = [
  // --- Gojuon dasar (46) ---
  CharacterItem(character: 'ア', romaji: 'a'),
  CharacterItem(character: 'イ', romaji: 'i'),
  CharacterItem(character: 'ウ', romaji: 'u'),
  CharacterItem(character: 'エ', romaji: 'e'),
  CharacterItem(character: 'オ', romaji: 'o'),
  CharacterItem(character: 'カ', romaji: 'ka'),
  CharacterItem(character: 'キ', romaji: 'ki'),
  CharacterItem(character: 'ク', romaji: 'ku'),
  CharacterItem(character: 'ケ', romaji: 'ke'),
  CharacterItem(character: 'コ', romaji: 'ko'),
  CharacterItem(character: 'サ', romaji: 'sa'),
  CharacterItem(character: 'シ', romaji: 'shi'),
  CharacterItem(character: 'ス', romaji: 'su'),
  CharacterItem(character: 'セ', romaji: 'se'),
  CharacterItem(character: 'ソ', romaji: 'so'),
  CharacterItem(character: 'タ', romaji: 'ta'),
  CharacterItem(character: 'チ', romaji: 'chi'),
  CharacterItem(character: 'ツ', romaji: 'tsu'),
  CharacterItem(character: 'テ', romaji: 'te'),
  CharacterItem(character: 'ト', romaji: 'to'),
  CharacterItem(character: 'ナ', romaji: 'na'),
  CharacterItem(character: 'ニ', romaji: 'ni'),
  CharacterItem(character: 'ヌ', romaji: 'nu'),
  CharacterItem(character: 'ネ', romaji: 'ne'),
  CharacterItem(character: 'ノ', romaji: 'no'),
  CharacterItem(character: 'ハ', romaji: 'ha'),
  CharacterItem(character: 'ヒ', romaji: 'hi'),
  CharacterItem(character: 'フ', romaji: 'fu'),
  CharacterItem(character: 'ヘ', romaji: 'he'),
  CharacterItem(character: 'ホ', romaji: 'ho'),
  CharacterItem(character: 'マ', romaji: 'ma'),
  CharacterItem(character: 'ミ', romaji: 'mi'),
  CharacterItem(character: 'ム', romaji: 'mu'),
  CharacterItem(character: 'メ', romaji: 'me'),
  CharacterItem(character: 'モ', romaji: 'mo'),
  CharacterItem(character: 'ヤ', romaji: 'ya'),
  CharacterItem(character: 'ユ', romaji: 'yu'),
  CharacterItem(character: 'ヨ', romaji: 'yo'),
  CharacterItem(character: 'ラ', romaji: 'ra'),
  CharacterItem(character: 'リ', romaji: 'ri'),
  CharacterItem(character: 'ル', romaji: 'ru'),
  CharacterItem(character: 'レ', romaji: 're'),
  CharacterItem(character: 'ロ', romaji: 'ro'),
  CharacterItem(character: 'ワ', romaji: 'wa'),
  CharacterItem(character: 'ヲ', romaji: 'wo'),
  CharacterItem(character: 'ン', romaji: 'n'),

  // --- Dakuten (20) ---
  CharacterItem(character: 'ガ', romaji: 'ga'),
  CharacterItem(character: 'ギ', romaji: 'gi'),
  CharacterItem(character: 'グ', romaji: 'gu'),
  CharacterItem(character: 'ゲ', romaji: 'ge'),
  CharacterItem(character: 'ゴ', romaji: 'go'),
  CharacterItem(character: 'ザ', romaji: 'za'),
  CharacterItem(character: 'ジ', romaji: 'ji'),
  CharacterItem(character: 'ズ', romaji: 'zu'),
  CharacterItem(character: 'ゼ', romaji: 'ze'),
  CharacterItem(character: 'ゾ', romaji: 'zo'),
  CharacterItem(character: 'ダ', romaji: 'da'),
  CharacterItem(character: 'ヂ', romaji: 'di'),
  CharacterItem(character: 'ヅ', romaji: 'du'),
  CharacterItem(character: 'デ', romaji: 'de'),
  CharacterItem(character: 'ド', romaji: 'do'),
  CharacterItem(character: 'バ', romaji: 'ba'),
  CharacterItem(character: 'ビ', romaji: 'bi'),
  CharacterItem(character: 'ブ', romaji: 'bu'),
  CharacterItem(character: 'ベ', romaji: 'be'),
  CharacterItem(character: 'ボ', romaji: 'bo'),

  // --- Handakuten (5) ---
  CharacterItem(character: 'パ', romaji: 'pa'),
  CharacterItem(character: 'ピ', romaji: 'pi'),
  CharacterItem(character: 'プ', romaji: 'pu'),
  CharacterItem(character: 'ペ', romaji: 'pe'),
  CharacterItem(character: 'ポ', romaji: 'po'),

  // --- Yoon (33) ---
  CharacterItem(character: 'キャ', romaji: 'kya'),
  CharacterItem(character: 'キュ', romaji: 'kyu'),
  CharacterItem(character: 'キョ', romaji: 'kyo'),
  CharacterItem(character: 'シャ', romaji: 'sha'),
  CharacterItem(character: 'シュ', romaji: 'shu'),
  CharacterItem(character: 'ショ', romaji: 'sho'),
  CharacterItem(character: 'チャ', romaji: 'cha'),
  CharacterItem(character: 'チュ', romaji: 'chu'),
  CharacterItem(character: 'チョ', romaji: 'cho'),
  CharacterItem(character: 'ニャ', romaji: 'nya'),
  CharacterItem(character: 'ニュ', romaji: 'nyu'),
  CharacterItem(character: 'ニョ', romaji: 'nyo'),
  CharacterItem(character: 'ヒャ', romaji: 'hya'),
  CharacterItem(character: 'ヒュ', romaji: 'hyu'),
  CharacterItem(character: 'ヒョ', romaji: 'hyo'),
  CharacterItem(character: 'ミャ', romaji: 'mya'),
  CharacterItem(character: 'ミュ', romaji: 'myu'),
  CharacterItem(character: 'ミョ', romaji: 'myo'),
  CharacterItem(character: 'リャ', romaji: 'rya'),
  CharacterItem(character: 'リュ', romaji: 'ryu'),
  CharacterItem(character: 'リョ', romaji: 'ryo'),
  CharacterItem(character: 'ギャ', romaji: 'gya'),
  CharacterItem(character: 'ギュ', romaji: 'gyu'),
  CharacterItem(character: 'ギョ', romaji: 'gyo'),
  CharacterItem(character: 'ジャ', romaji: 'ja'),
  CharacterItem(character: 'ジュ', romaji: 'ju'),
  CharacterItem(character: 'ジョ', romaji: 'jo'),
  CharacterItem(character: 'ビャ', romaji: 'bya'),
  CharacterItem(character: 'ビュ', romaji: 'byu'),
  CharacterItem(character: 'ビョ', romaji: 'byo'),
  CharacterItem(character: 'ピャ', romaji: 'pya'),
  CharacterItem(character: 'ピュ', romaji: 'pyu'),
  CharacterItem(character: 'ピョ', romaji: 'pyo'),
];
