# File: pubspec.yaml
# Konfigurasi proyek Flutter, termasuk dependensi dan assets.
# Hari 3: Tambah deklarasi assets untuk gambar dummy.
# Nanti di Hari 21+, kita tambah dependensi seperti google_fonts, provider, dll.

name: letterhanna
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Assets: Deklarasi folder untuk gambar dummy.
  # Pastikan folder assets/images/ ada di root proyek.
  assets:
    - assets/images/font_preview1.png
    - assets/images/font_preview2.png
    - assets/images/font_preview3.png