name: neon_whisper
description: "Aplikasi salam interaktif dengan efek neon glow bergaya Synthwave"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino icons untuk iOS style icons (opsional)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting untuk code quality
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Jika ingin menambahkan custom font nanti, uncomment dan tambahkan di sini
  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: fonts/Orbitron-Regular.ttf
  #       - asset: fonts/Orbitron-Bold.ttf
  #         weight: 700