// Data suku kata lengkap — ratusan kartu, metode TK per suku kata
// Diorganisasi per bab vokal dan tingkat kesulitan

class SyllableData {
  SyllableData._();

  // Setiap item adalah List<String> — bagian-bagian suku kata dalam satu kartu
  // Jika hanya 1 elemen = satu suku kata penuh
  // Jika 2 elemen = dua suku kata (warna bergantian)

  static const List<Map<String, dynamic>> chapters = [
    {
      'title': 'Vokal A — Ba, Ca, Da',
      'subtitle': '48 kartu • Tingkat 1',
      'gradientIndex': 0,
      'cards': [
        // Huruf tunggal
        ['a'],
        ['b'],
        ['c'],
        ['d'],

        // Suku kata ba
        ['ba'],
        ['a', 'ba'],
        ['ba', 'ba'],
        ['ba', 'a'],

        // Suku kata ca
        ['ca'],
        ['a', 'ca'],
        ['ca', 'ca'],
        ['ca', 'ba'],
        ['ba', 'ca'],

        // Suku kata da
        ['da'],
        ['a', 'da'],
        ['da', 'da'],
        ['da', 'ba'],
        ['ba', 'da'],
        ['da', 'ca'],
        ['ca', 'da'],

        // Suku kata fa
        ['fa'],
        ['fa', 'da'],
        ['da', 'fa'],
        ['fa', 'fa'],

        // Suku kata ga
        ['ga'],
        ['ga', 'ga'],
        ['ba', 'ga'],
        ['ga', 'da'],

        // Suku kata ha
        ['ha'],
        ['ha', 'ha'],
        ['ca', 'ha'],
        ['ha', 'da'],

        // Suku kata ja
        ['ja'],
        ['ja', 'ja'],
        ['ba', 'ja'],
        ['ja', 'ga'],

        // Suku kata ka
        ['ka'],
        ['ka', 'ka'],
        ['ba', 'ka'],
        ['ka', 'da'],
        ['ka', 'ja'],
        ['ja', 'ka'],

        // Suku kata la
        ['la'],
        ['la', 'la'],
        ['ba', 'la'],
        ['la', 'ga'],
        ['la', 'ba'],
        ['ga', 'la'],
        ['la', 'da'],
        ['da', 'la'],
      ],
    },
    {
      'title': 'Vokal A — Ma, Na, Pa',
      'subtitle': '48 kartu • Tingkat 1',
      'gradientIndex': 0,
      'cards': [
        // Suku kata ma
        ['ma'],
        ['ma', 'ma'],
        ['ba', 'ma'],
        ['ma', 'da'],
        ['la', 'ma'],
        ['ma', 'la'],
        ['ma', 'ga'],
        ['ga', 'ma'],

        // Suku kata na
        ['na'],
        ['na', 'na'],
        ['ba', 'na'],
        ['na', 'ma'],
        ['ma', 'na'],
        ['na', 'da'],
        ['da', 'na'],
        ['na', 'ka'],

        // Suku kata pa
        ['pa'],
        ['pa', 'pa'],
        ['ba', 'pa'],
        ['pa', 'da'],
        ['la', 'pa'],
        ['pa', 'na'],
        ['na', 'pa'],
        ['pa', 'ka'],

        // Suku kata ra
        ['ra'],
        ['ra', 'ra'],
        ['ba', 'ra'],
        ['ra', 'da'],
        ['ka', 'ra'],
        ['ra', 'ma'],
        ['ma', 'ra'],
        ['ra', 'na'],

        // Suku kata sa
        ['sa'],
        ['sa', 'sa'],
        ['ba', 'sa'],
        ['sa', 'da'],
        ['la', 'sa'],
        ['sa', 'na'],
        ['na', 'sa'],
        ['sa', 'ra'],

        // Suku kata ta
        ['ta'],
        ['ta', 'ta'],
        ['ba', 'ta'],
        ['ta', 'da'],
        ['la', 'ta'],
        ['ta', 'na'],
        ['na', 'ta'],
        ['ta', 'ra'],
      ],
    },
    {
      'title': 'Vokal A — Va, Wa, Za',
      'subtitle': '36 kartu • Tingkat 1',
      'gradientIndex': 0,
      'cards': [
        // Suku kata va
        ['va'],
        ['va', 'va'],
        ['ba', 'va'],
        ['va', 'da'],
        ['la', 'va'],
        ['va', 'na'],

        // Suku kata wa
        ['wa'],
        ['wa', 'wa'],
        ['ba', 'wa'],
        ['wa', 'da'],
        ['la', 'wa'],
        ['wa', 'na'],
        ['na', 'wa'],
        ['wa', 'ra'],

        // Suku kata xa
        ['xa'],
        ['xa', 'xa'],

        // Suku kata ya
        ['ya'],
        ['ya', 'ya'],
        ['ba', 'ya'],
        ['ya', 'da'],
        ['la', 'ya'],
        ['ya', 'na'],
        ['na', 'ya'],
        ['ya', 'ra'],
        ['ma', 'ya'],
        ['ya', 'ma'],

        // Suku kata za
        ['za'],
        ['za', 'za'],
        ['ba', 'za'],
        ['za', 'da'],
        ['la', 'za'],
        ['za', 'na'],
        ['na', 'za'],
        ['za', 'ra'],
        ['ma', 'za'],
        ['za', 'ma'],
        ['a', 'za'],
      ],
    },
    {
      'title': 'Vokal I — Bi, Ci, Di',
      'subtitle': '48 kartu • Tingkat 2',
      'gradientIndex': 1,
      'cards': [
        // Huruf tunggal
        ['i'],

        // Suku kata bi
        ['bi'],
        ['i', 'bi'],
        ['bi', 'bi'],
        ['bi', 'i'],
        ['a', 'bi'],
        ['bi', 'a'],
        ['ba', 'bi'],
        ['bi', 'ba'],

        // Suku kata ci
        ['ci'],
        ['i', 'ci'],
        ['ci', 'ci'],
        ['ci', 'bi'],
        ['bi', 'ci'],
        ['ca', 'ci'],
        ['ci', 'ca'],

        // Suku kata di
        ['di'],
        ['i', 'di'],
        ['di', 'di'],
        ['di', 'bi'],
        ['bi', 'di'],
        ['da', 'di'],
        ['di', 'da'],
        ['di', 'ci'],

        // Suku kata fi
        ['fi'],
        ['fi', 'di'],
        ['di', 'fi'],
        ['fi', 'fi'],

        // Suku kata gi
        ['gi'],
        ['gi', 'gi'],
        ['bi', 'gi'],
        ['gi', 'di'],

        // Suku kata hi
        ['hi'],
        ['hi', 'hi'],
        ['ci', 'hi'],
        ['hi', 'di'],

        // Suku kata ji
        ['ji'],
        ['ji', 'ji'],
        ['bi', 'ji'],
        ['ji', 'gi'],

        // Suku kata ki
        ['ki'],
        ['ki', 'ki'],
        ['bi', 'ki'],
        ['ki', 'di'],
        ['ki', 'ji'],

        // Suku kata li
        ['li'],
        ['li', 'li'],
        ['bi', 'li'],
        ['li', 'gi'],
        ['li', 'bi'],
      ],
    },
    {
      'title': 'Vokal I — Mi, Ni, Pi',
      'subtitle': '40 kartu • Tingkat 2',
      'gradientIndex': 1,
      'cards': [
        // Suku kata mi
        ['mi'],
        ['mi', 'mi'],
        ['bi', 'mi'],
        ['mi', 'di'],
        ['li', 'mi'],
        ['mi', 'li'],
        ['mi', 'gi'],
        ['gi', 'mi'],

        // Suku kata ni
        ['ni'],
        ['ni', 'ni'],
        ['bi', 'ni'],
        ['ni', 'mi'],
        ['mi', 'ni'],
        ['ni', 'di'],
        ['di', 'ni'],
        ['ni', 'ki'],

        // Suku kata pi
        ['pi'],
        ['pi', 'pi'],
        ['bi', 'pi'],
        ['pi', 'di'],
        ['li', 'pi'],
        ['pi', 'ni'],
        ['ni', 'pi'],
        ['pi', 'ki'],

        // Suku kata ri
        ['ri'],
        ['ri', 'ri'],
        ['bi', 'ri'],
        ['ri', 'di'],
        ['ki', 'ri'],
        ['ri', 'mi'],

        // Suku kata si
        ['si'],
        ['si', 'si'],
        ['bi', 'si'],
        ['si', 'di'],
        ['li', 'si'],
        ['si', 'ni'],

        // Suku kata ti
        ['ti'],
        ['ti', 'ti'],
        ['bi', 'ti'],
        ['ti', 'di'],
      ],
    },
    {
      'title': 'Vokal U — Bu, Cu, Du',
      'subtitle': '48 kartu • Tingkat 2',
      'gradientIndex': 2,
      'cards': [
        ['u'],
        ['bu'],
        ['u', 'bu'],
        ['bu', 'bu'],
        ['bu', 'u'],
        ['a', 'bu'],
        ['bu', 'a'],
        ['ba', 'bu'],
        ['bu', 'ba'],
        ['bi', 'bu'],
        ['bu', 'bi'],
        ['cu'],
        ['u', 'cu'],
        ['cu', 'cu'],
        ['cu', 'bu'],
        ['bu', 'cu'],
        ['ca', 'cu'],
        ['cu', 'ca'],
        ['ci', 'cu'],
        ['cu', 'ci'],
        ['du'],
        ['u', 'du'],
        ['du', 'du'],
        ['du', 'bu'],
        ['bu', 'du'],
        ['da', 'du'],
        ['du', 'da'],
        ['di', 'du'],
        ['du', 'di'],
        ['fu'],
        ['fu', 'du'],
        ['gu'],
        ['gu', 'gu'],
        ['bu', 'gu'],
        ['gu', 'du'],
        ['hu'],
        ['hu', 'hu'],
        ['cu', 'hu'],
        ['hu', 'du'],
        ['ju'],
        ['ju', 'ju'],
        ['bu', 'ju'],
        ['ju', 'gu'],
        ['ku'],
        ['ku', 'ku'],
        ['bu', 'ku'],
        ['ku', 'du'],
        ['lu'],
        ['lu', 'lu'],
      ],
    },
    {
      'title': 'Vokal E — Be, Ce, De',
      'subtitle': '48 kartu • Tingkat 3',
      'gradientIndex': 3,
      'cards': [
        ['e'],
        ['be'],
        ['e', 'be'],
        ['be', 'be'],
        ['be', 'a'],
        ['be', 'i'],
        ['be', 'u'],
        ['a', 'be'],
        ['ba', 'be'],
        ['bi', 'be'],
        ['bu', 'be'],
        ['ce'],
        ['e', 'ce'],
        ['ce', 'ce'],
        ['ce', 'be'],
        ['be', 'ce'],
        ['ca', 'ce'],
        ['ci', 'ce'],
        ['cu', 'ce'],
        ['de'],
        ['e', 'de'],
        ['de', 'de'],
        ['de', 'be'],
        ['be', 'de'],
        ['da', 'de'],
        ['di', 'de'],
        ['du', 'de'],
        ['fe'],
        ['fe', 'de'],
        ['ge'],
        ['ge', 'ge'],
        ['be', 'ge'],
        ['ge', 'de'],
        ['he'],
        ['he', 'he'],
        ['ce', 'he'],
        ['je'],
        ['je', 'je'],
        ['be', 'je'],
        ['ke'],
        ['ke', 'ke'],
        ['be', 'ke'],
        ['le'],
        ['le', 'le'],
        ['be', 'le'],
        ['me'],
        ['me', 'me'],
        ['be', 'me'],
      ],
    },
    {
      'title': 'Vokal O — Bo, Co, Do',
      'subtitle': '48 kartu • Tingkat 3',
      'gradientIndex': 4,
      'cards': [
        ['o'],
        ['bo'],
        ['o', 'bo'],
        ['bo', 'bo'],
        ['bo', 'a'],
        ['bo', 'i'],
        ['bo', 'u'],
        ['a', 'bo'],
        ['ba', 'bo'],
        ['bi', 'bo'],
        ['bu', 'bo'],
        ['co'],
        ['o', 'co'],
        ['co', 'co'],
        ['co', 'bo'],
        ['bo', 'co'],
        ['ca', 'co'],
        ['ci', 'co'],
        ['cu', 'co'],
        ['do'],
        ['o', 'do'],
        ['do', 'do'],
        ['do', 'bo'],
        ['bo', 'do'],
        ['da', 'do'],
        ['di', 'do'],
        ['du', 'do'],
        ['fo'],
        ['fo', 'do'],
        ['go'],
        ['go', 'go'],
        ['bo', 'go'],
        ['go', 'do'],
        ['ho'],
        ['ho', 'ho'],
        ['co', 'ho'],
        ['jo'],
        ['jo', 'jo'],
        ['bo', 'jo'],
        ['ko'],
        ['ko', 'ko'],
        ['bo', 'ko'],
        ['lo'],
        ['lo', 'lo'],
        ['bo', 'lo'],
        ['mo'],
        ['mo', 'mo'],
        ['bo', 'mo'],
      ],
    },
    {
      'title': 'Gabungan Semua Vokal',
      'subtitle': '60 kartu • Tingkat 4',
      'gradientIndex': 5,
      'cards': [
        ['ba', 'bi'],
        ['bi', 'ba'],
        ['bu', 'ba'],
        ['ba', 'bu'],
        ['be', 'ba'],
        ['ba', 'be'],
        ['bo', 'ba'],
        ['ba', 'bo'],
        ['ca', 'ci'],
        ['ci', 'ca'],
        ['cu', 'ca'],
        ['ca', 'cu'],
        ['ce', 'ca'],
        ['ca', 'ce'],
        ['co', 'ca'],
        ['ca', 'co'],
        ['da', 'di'],
        ['di', 'da'],
        ['du', 'da'],
        ['da', 'du'],
        ['de', 'da'],
        ['da', 'de'],
        ['do', 'da'],
        ['da', 'do'],
        ['ga', 'gi'],
        ['gi', 'ga'],
        ['gu', 'ga'],
        ['ga', 'gu'],
        ['ja', 'ji'],
        ['ji', 'ja'],
        ['ju', 'ja'],
        ['ja', 'ju'],
        ['ka', 'ki'],
        ['ki', 'ka'],
        ['ku', 'ka'],
        ['ka', 'ku'],
        ['la', 'li'],
        ['li', 'la'],
        ['lu', 'la'],
        ['la', 'lu'],
        ['ma', 'mi'],
        ['mi', 'ma'],
        ['mu', 'ma'],
        ['ma', 'mu'],
        ['na', 'ni'],
        ['ni', 'na'],
        ['nu', 'na'],
        ['na', 'nu'],
        ['pa', 'pi'],
        ['pi', 'pa'],
        ['pu', 'pa'],
        ['pa', 'pu'],
        ['ra', 'ri'],
        ['ri', 'ra'],
        ['ru', 'ra'],
        ['ra', 'ru'],
        ['sa', 'si'],
        ['si', 'sa'],
        ['su', 'sa'],
        ['sa', 'su'],
      ],
    },
    {
      'title': 'Suku Kata Tiga',
      'subtitle': '56 kartu • Tingkat 5',
      'gradientIndex': 6,
      'cards': [
        ['ba', 'ca', 'bi'],
        ['ca', 'di', 'ma'],
        ['ba', 'ju', 'ri'],
        ['da', 'gi', 'bu'],
        ['ga', 'ra', 'si'],
        ['la', 'ri', 'bu'],
        ['ma', 'ta', 'ri'],
        ['na', 'si', 'bu'],
        ['pa', 'gi', 'ba'],
        ['ra', 'bu', 'ta'],
        ['sa', 'pi', 'tu'],
        ['ta', 'bu', 'la'],
        ['bu', 'ku', 'ti'],
        ['cu', 'cu', 'ru'],
        ['du', 'ri', 'an'],
        ['ga', 'bu', 'si'],
        ['hu', 'jan', 'i'],
        ['i', 'bu', 'ku'],
        ['ja', 'ri', 'ta'],
        ['ka', 'ki', 'mu'],
        ['la', 'bu', 'ci'],
        ['ma', 'ka', 'na'],
        ['na', 'bu', 'si'],
        ['o', 'ba', 'ti'],
        ['pa', 'ku', 'si'],
        ['ra', 'gi', 'la'],
        ['sa', 'pu', 'ta'],
        ['ta', 'li', 'na'],
        ['u', 'bi', 'tu'],
        ['wa', 'ku', 'ti'],
        ['ya', 'ki', 'sa'],
        ['za', 'gi', 'bu'],
        ['be', 'li', 'ku'],
        ['ce', 'ri', 'ta'],
        ['de', 'bu', 'mi'],
        ['fe', 'ri', 'ba'],
        ['ge', 'mu', 'ri'],
        ['he', 'la', 'bu'],
        ['je', 'ri', 'ta'],
        ['ke', 'li', 'pa'],
        ['le', 'ba', 'ri'],
        ['me', 'ri', 'bu'],
        ['ne', 'la', 'bu'],
        ['pe', 'li', 'ta'],
        ['re', 'bu', 'sa'],
        ['se', 'la', 'ti'],
        ['te', 'ri', 'bu'],
        ['bo', 'li', 'ta'],
        ['co', 'ba', 'ri'],
        ['do', 'li', 'na'],
        ['fo', 'ri', 'ma'],
        ['go', 're', 'na'],
        ['ho', 'ri', 'ta'],
        ['jo', 'li', 'na'],
        ['ko', 're', 'ti'],
        ['lo', 'ba', 'ri'],
      ],
    },

    // ═══════════════════════════════════════════════════════════════
    // BAB 11 — HURUF KONSONAN AKHIR: -k, -p, -t
    // ═══════════════════════════════════════════════════════════════
    {
      'title': 'Konsonan Akhir — k, p, t',
      'subtitle': '54 kartu • Tingkat 6',
      'gradientIndex': 6,
      'cards': [
        // ─ akhiran -k ─
        ['ak'],
        ['ik'],
        ['uk'],
        ['ek'],
        ['ok'],
        ['bak'],
        ['pak'],
        ['mak'],
        ['nak'],
        ['kak'],
        ['dak'],
        ['tak'],
        ['rak'],
        ['sak'],
        ['bik'],
        ['tik'],
        ['naik'],
        ['baik'],
        ['kaik'],
        ['bu', 'kak'],
        ['ka', 'nak'],
        ['ma', 'nak'],
        ['ba', 'pak'],
        ['ka', 'pak'],
        ['la', 'pik'],
        ['bo', 'bok'],
        ['ko', 'kok'],
        // ─ akhiran -p ─
        ['ap'],
        ['ip'],
        ['up'],
        ['ep'],
        ['op'],
        ['bap'],
        ['cap'],
        ['gap'],
        ['kap'],
        ['lap'],
        ['map'],
        ['rap'],
        ['sap'],
        ['tap'],
        ['tip'],
        ['dip'],
        ['kup'],
        ['pup'],
        ['su', 'ap'],
        ['ma', 'sap'],
        ['ba', 'lap'],
        ['bu', 'kap'],
        // ─ akhiran -t ─
        ['at'],
        ['it'],
        ['ut'],
        ['et'],
        ['ot'],
        ['bat'],
        ['cat'],
        ['dat'],
        ['gat'],
        ['hat'],
        ['jat'],
        ['kat'],
        ['lat'],
        ['mat'],
        ['nat'],
        ['pat'],
        ['rat'],
        ['sat'],
        ['tat'],
        ['bit'],
        ['dit'],
        ['git'],
        ['kit'],
        ['lit'],
        ['mit'],
        ['nit'],
        ['pit'],
        ['cut'],
        ['gut'],
        ['put'],
        ['but'],
        ['bot'],
        ['dot'],
        ['got'],
        ['kot'],
        ['lot'],
        ['mot'],
        ['pot'],
        ['rot'],
        ['ba', 'lat'],
        ['ma', 'kat'],
        ['ra', 'kit'],
        ['sa', 'kit'],
        ['bu', 'kit'],
        ['co', 'rat'],
        ['mo', 'rot'],
        ['ka', 'ret'],
        ['se', 'pat'],
        ['li', 'pat'],
        ['ku', 'pat'],
        ['ki', 'lat'],
        ['pi', 'kat'],
        ['ri', 'but'],
      ],
    },

    // ═══════════════════════════════════════════════════════════════
    // BAB 12 — HURUF KONSONAN AKHIR: -m, -n, -l, -r, -s
    // ═══════════════════════════════════════════════════════════════
    {
      'title': 'Konsonan Akhir — m, n, l, r, s',
      'subtitle': '60 kartu • Tingkat 6',
      'gradientIndex': 7,
      'cards': [
        // ─ akhiran -m ─
        ['am'],
        ['im'],
        ['um'],
        ['em'],
        ['om'],
        ['bam'],
        ['cam'],
        ['dam'],
        ['gam'],
        ['ham'],
        ['jam'],
        ['kam'],
        ['lam'],
        ['mam'],
        ['nam'],
        ['pam'],
        ['ram'],
        ['sam'],
        ['tam'],
        ['rim'],
        ['dim'],
        ['kim'],
        ['bum'],
        ['gum'],
        ['kum'],
        ['rum'],
        ['ma', 'lam'],
        ['sa', 'lam'],
        ['pa', 'ham'],
        ['ka', 'lam'],
        ['ta', 'nam'],
        // ─ akhiran -n ─
        ['an'],
        ['in'],
        ['un'],
        ['en'],
        ['on'],
        ['ban'],
        ['can'],
        ['dan'],
        ['gan'],
        ['han'],
        ['jan'],
        ['kan'],
        ['lan'],
        ['man'],
        ['nan'],
        ['pan'],
        ['ran'],
        ['san'],
        ['tan'],
        ['bin'],
        ['cin'],
        ['din'],
        ['gin'],
        ['kin'],
        ['lin'],
        ['min'],
        ['nin'],
        ['pin'],
        ['bun'],
        ['dun'],
        ['gun'],
        ['kun'],
        ['lun'],
        ['mun'],
        ['nun'],
        ['pun'],
        ['run'],
        ['ben'],
        ['den'],
        ['gen'],
        ['ken'],
        ['len'],
        ['men'],
        ['bon'],
        ['con'],
        ['don'],
        ['gon'],
        ['kon'],
        ['lon'],
        ['mon'],
        ['non'],
        ['ba', 'dan'],
        ['ja', 'lan'],
        ['ma', 'kan'],
        ['ta', 'han'],
        ['bu', 'lan'],
        ['tu', 'han'],
        ['bi', 'lan'],
        ['ki', 'ran'],
        ['pi', 'san'],
        ['bo', 'lon'],
        // ─ akhiran -l ─
        ['al'],
        ['il'],
        ['ul'],
        ['el'],
        ['ol'],
        ['bal'],
        ['cal'],
        ['dal'],
        ['gal'],
        ['hal'],
        ['jal'],
        ['kal'],
        ['lal'],
        ['mal'],
        ['nal'],
        ['pal'],
        ['ral'],
        ['sal'],
        ['tal'],
        ['bil'],
        ['cil'],
        ['dil'],
        ['gil'],
        ['kil'],
        ['nil'],
        ['pil'],
        ['ril'],
        ['bul'],
        ['dul'],
        ['gul'],
        ['kul'],
        ['mul'],
        ['pul'],
        ['rul'],
        ['sul'],
        ['a', 'sal'],
        ['ba', 'tal'],
        ['ha', 'lal'],
        ['ka', 'dal'],
        ['ma', 'hal'],
        ['pa', 'tal'],
        ['ta', 'kal'],
        ['bu', 'lul'],
        // ─ akhiran -r ─
        ['ar'],
        ['ir'],
        ['ur'],
        ['er'],
        ['or'],
        ['bar'],
        ['car'],
        ['dar'],
        ['gar'],
        ['har'],
        ['jar'],
        ['kar'],
        ['lar'],
        ['mar'],
        ['nar'],
        ['par'],
        ['rar'],
        ['sar'],
        ['tar'],
        ['bir'],
        ['cir'],
        ['dir'],
        ['gir'],
        ['kir'],
        ['lir'],
        ['mir'],
        ['nir'],
        ['pir'],
        ['rir'],
        ['sir'],
        ['tir'],
        ['bur'],
        ['dur'],
        ['gur'],
        ['kur'],
        ['lur'],
        ['mur'],
        ['nur'],
        ['pur'],
        ['sur'],
        ['tur'],
        ['a', 'kar'],
        ['ba', 'kar'],
        ['la', 'par'],
        ['pa', 'sar'],
        ['sa', 'bar'],
        ['ta', 'tar'],
        ['bu', 'sur'],
        ['ku', 'tur'],
        // ─ akhiran -s ─
        ['as'],
        ['is'],
        ['us'],
        ['es'],
        ['os'],
        ['bas'],
        ['das'],
        ['gas'],
        ['has'],
        ['kas'],
        ['las'],
        ['mas'],
        ['nas'],
        ['pas'],
        ['ras'],
        ['sas'],
        ['tas'],
        ['bis'],
        ['dis'],
        ['gis'],
        ['kis'],
        ['lis'],
        ['mis'],
        ['nis'],
        ['pis'],
        ['bus'],
        ['dus'],
        ['gus'],
        ['kus'],
        ['mus'],
        ['nus'],
        ['pus'],
        ['rus'],
        ['tus'],
        ['a', 'las'],
        ['ba', 'las'],
        ['ga', 'las'],
        ['ka', 'las'],
        ['ma', 'las'],
        ['pa', 'las'],
        ['ta', 'las'],
        ['ba', 'his'],
        ['ma', 'nis'],
        ['pa', 'nis'],
        ['ta', 'nis'],
        ['bo', 'ros'],
        ['po', 'ros'],
        ['to', 'ros'],
      ],
    },

    // ═══════════════════════════════════════════════════════════════
    // BAB 13 — SUKU KATA DENGAN NG
    // ═══════════════════════════════════════════════════════════════
    {
      'title': 'Suku Kata — NG',
      'subtitle': '52 kartu • Tingkat 7',
      'gradientIndex': 8,
      'cards': [
        // ─ ng sebagai suku kata awal ─
        ['nga'],
        ['ngi'],
        ['ngu'],
        ['nge'],
        ['ngo'],
        ['nga', 'nga'],
        ['ngi', 'ngi'],
        ['ngu', 'ngu'],
        // ─ ng sebagai akhiran ─
        ['ang'],
        ['ing'],
        ['ung'],
        ['eng'],
        ['ong'],
        ['bang'],
        ['dang'],
        ['gang'],
        ['hang'],
        ['jang'],
        ['kang'],
        ['lang'],
        ['mang'],
        ['nang'],
        ['pang'],
        ['rang'],
        ['sang'],
        ['tang'],
        ['wang'],
        ['yang'],
        ['bing'],
        ['cing'],
        ['ding'],
        ['ging'],
        ['king'],
        ['ling'],
        ['ming'],
        ['ning'],
        ['ping'],
        ['ring'],
        ['sing'],
        ['ting'],
        ['bung'],
        ['dung'],
        ['gung'],
        ['kung'],
        ['lung'],
        ['mung'],
        ['nung'],
        ['pung'],
        ['rung'],
        ['sung'],
        ['tung'],
        ['bong'],
        ['dong'],
        ['gong'],
        ['kong'],
        ['long'],
        ['mong'],
        ['nong'],
        ['pong'],
        ['rong'],
        ['song'],
        ['tong'],
        // ─ kata dengan ng ─
        ['a', 'bang'],
        ['a', 'bing'],
        ['u', 'lang'],
        ['sa', 'yang'],
        ['ma', 'lang'],
        ['ga', 'lang'],
        ['ba', 'rang'],
        ['ta', 'nang'],
        ['ka', 'sang'],
        ['pi', 'sang'],
        ['bi', 'lang'],
        ['hi', 'lang'],
        ['mi', 'ring'],
        ['di', 'ng-in'],
        ['ku', 'ning'],
        ['bu', 'rong'],
        ['ko', 'song'],
        ['go', 'rong'],
        ['bo', 'long'],
        ['to', 'long'],
        ['du', 'kung'],
        ['lu', 'rung'],
        ['gu', 'nung'],
        ['a', 'sang'],
        ['ba', 'ting'],
        ['la', 'rang'],
        ['pa', 'rang'],
        ['ra', 'wang'],
        ['sa', 'rang'],
        ['ta', 'rang'],
        ['ha', 'rang'],
        ['ka', 'rang'],
        ['da', 'tang'],
        ['ja', 'rang'],
        ['ma', 'sang'],
        ['na', 'nang'],
        ['ga', 'rang'],
        ['wa', 'lang'],
        ['ya', 'ng-an'],
        ['za', 'rang'],
      ],
    },

    // ═══════════════════════════════════════════════════════════════
    // BAB 14 — SUKU KATA DENGAN NY
    // ═══════════════════════════════════════════════════════════════
    {
      'title': 'Suku Kata — NY',
      'subtitle': '48 kartu • Tingkat 7',
      'gradientIndex': 9,
      'cards': [
        // ─ ny sebagai suku kata awal ─
        ['nya'],
        ['nyi'],
        ['nyu'],
        ['nye'],
        ['nyo'],
        ['nya', 'nya'],
        ['nyi', 'nyi'],
        ['nyu', 'nyu'],
        ['nye', 'nye'],
        ['nyo', 'nyo'],
        // ─ ny di tengah kata ─
        ['a', 'nya'],
        ['i', 'nya'],
        ['u', 'nya'],
        ['e', 'nya'],
        ['o', 'nya'],
        ['ba', 'nya'],
        ['ca', 'nya'],
        ['da', 'nya'],
        ['ga', 'nya'],
        ['ha', 'nya'],
        ['ja', 'nya'],
        ['ka', 'nya'],
        ['la', 'nya'],
        ['ma', 'nya'],
        ['na', 'nya'],
        ['pa', 'nya'],
        ['ra', 'nya'],
        ['sa', 'nya'],
        ['ta', 'nya'],
        ['wa', 'nya'],
        // ─ ny kombinasi lebih lanjut ─
        ['bi', 'nya'],
        ['di', 'nya'],
        ['gi', 'nya'],
        ['ki', 'nya'],
        ['li', 'nya'],
        ['mi', 'nya'],
        ['ni', 'nya'],
        ['pi', 'nya'],
        ['ri', 'nya'],
        ['si', 'nya'],
        ['bu', 'nya'],
        ['du', 'nya'],
        ['gu', 'nya'],
        ['ku', 'nya'],
        ['mu', 'nya'],
        ['nu', 'nya'],
        ['pu', 'nya'],
        ['ru', 'nya'],
        ['su', 'nya'],
        ['tu', 'nya'],
        ['bo', 'nya'],
        ['co', 'nya'],
        ['do', 'nya'],
        ['go', 'nya'],
        ['ko', 'nya'],
        ['lo', 'nya'],
        ['mo', 'nya'],
        ['no', 'nya'],
        ['po', 'nya'],
        ['ro', 'nya'],
        ['so', 'nya'],
        ['to', 'nya'],
        // ─ kata dua suku kata ─
        ['nya', 'ri'],
        ['nyu', 'r'],
        ['nyi', 'r'],
        ['nya', 'la'],
        ['nyo', 'nya'],
        ['nya', 'nyi'],
        ['sa', 'nyi'],
        ['ma', 'nyi'],
        ['se', 'nyi'],
        ['ke', 'nyi'],
        ['pe', 'nyi'],
        ['le', 'nyi'],
        ['me', 'nyi'],
        ['de', 'nyi'],
        ['ge', 'nyi'],
        ['te', 'nyi'],
      ],
    },

    // ═══════════════════════════════════════════════════════════════
    // BAB 15 — DIFTONG: ai, au, oi
    // ═══════════════════════════════════════════════════════════════
    {
      'title': 'Diftong — ai, au, oi',
      'subtitle': '54 kartu • Tingkat 8',
      'gradientIndex': 0,
      'cards': [
        // ─ diftong ai ─
        ['ai'],
        ['bai'],
        ['cai'],
        ['dai'],
        ['gai'],
        ['hai'],
        ['jai'],
        ['kai'],
        ['lai'],
        ['mai'],
        ['nai'],
        ['pai'],
        ['rai'],
        ['sai'],
        ['tai'],
        ['wai'],
        ['yai'],
        ['a', 'lai'],
        ['ba', 'lai'],
        ['da', 'lai'],
        ['ga', 'lai'],
        ['ka', 'lai'],
        ['ma', 'lai'],
        ['pa', 'lai'],
        ['ra', 'mai'],
        ['sa', 'lai'],
        ['ta', 'mai'],
        ['bi', 'lai'],
        ['ki', 'lai'],
        ['li', 'lai'],
        ['pi', 'lai'],
        ['ri', 'lai'],
        ['su', 'dai'],
        ['ku', 'lai'],
        ['du', 'tai'],
        ['bo', 'lai'],
        ['ko', 'tai'],
        // ─ diftong au ─
        ['au'],
        ['bau'],
        ['cau'],
        ['dau'],
        ['gau'],
        ['hau'],
        ['jau'],
        ['kau'],
        ['lau'],
        ['mau'],
        ['nau'],
        ['pau'],
        ['rau'],
        ['sau'],
        ['tau'],
        ['a', 'tau'],
        ['a', 'mau'],
        ['ha', 'rau'],
        ['ka', 'lau'],
        ['ma', 'sau'],
        ['pa', 'sau'],
        ['ra', 'mau'],
        ['sa', 'dau'],
        ['ta', 'hau'],
        ['pi', 'sau'],
        ['ri', 'bau'],
        ['si', 'rau'],
        ['bu', 'rau'],
        ['ku', 'mau'],
        ['pu', 'lau'],
        ['bo', 'lau'],
        ['ko', 'lau'],
        ['po', 'lau'],
        ['ro', 'mau'],
        ['so', 'rau'],
        // ─ diftong oi ─
        ['oi'],
        ['boi'],
        ['doi'],
        ['goi'],
        ['koi'],
        ['loi'],
        ['moi'],
        ['noi'],
        ['poi'],
        ['roi'],
        ['soi'],
        ['toi'],
        ['a', 'moi'],
        ['ba', 'loi'],
        ['ka', 'loi'],
        ['ma', 'roi'],
        ['sa', 'poi'],
        ['ta', 'roi'],
        ['bu', 'poi'],
        ['ko', 'roi'],
        ['lo', 'roi'],
        ['mo', 'roi'],
        ['po', 'roi'],
        ['ro', 'poi'],
        ['so', 'roi'],
        ['to', 'roi'],
      ],
    },

    // ═══════════════════════════════════════════════════════════════
    // BAB 16 — GABUNGAN: Konsonan Akhir + NG/NY + Diftong
    // ═══════════════════════════════════════════════════════════════
    {
      'title': 'Gabungan Lanjutan',
      'subtitle': '56 kartu • Tingkat 9',
      'gradientIndex': 5,
      'cards': [
        // ─ konsonan akhir + diftong ─
        ['nai', 'kan'],
        ['mai', 'nan'],
        ['pai', 'sar'],
        ['tai', 'kan'],
        ['lai', 'nan'],
        ['bai', 'kan'],
        ['dai', 'kan'],
        ['kai', 'tan'],
        ['sau', 'dar'],
        ['mau', 'kan'],
        ['pau', 'san'],
        ['tau', 'kan'],
        ['lau', 'kan'],
        ['kau', 'nan'],
        ['rau', 'tan'],
        ['hau', 'san'],
        // ─ ng + vokal ─
        ['ngan', 'ti'],
        ['nging', 'in'],
        ['ngap', 'us'],
        ['ngar', 'ai'],
        ['ngas', 'an'],
        ['nga', 'lai'],
        ['ngi', 'lai'],
        ['ngu', 'lai'],
        ['nge', 'roi'],
        ['ngo', 'bai'],
        // ─ ny + vokal ─
        ['nya', 'nyi'],
        ['nyi', 'nya'],
        ['nyu', 'nyi'],
        ['nye', 'nya'],
        ['nyo', 'nyi'],
        // ─ kata kompleks ─
        ['sa', 'yang'],
        ['se', 'nang'],
        ['ma', 'sang'],
        ['pi', 'sang'],
        ['gu', 'nung'],
        ['ba', 'rang'],
        ['ja', 'rang'],
        ['ka', 'rang'],
        ['la', 'rang'],
        ['ma', 'rang'],
        ['pa', 'rang'],
        ['ta', 'rang'],
        ['bo', 'long'],
        ['ko', 'song'],
        ['go', 'rong'],
        ['to', 'long'],
        ['du', 'kung'],
        ['ku', 'ning'],
        ['bu', 'rong'],
        ['da', 'tang'],
        ['hi', 'lang'],
        ['bi', 'lang'],
        ['u', 'lang'],
        ['me', 'nang'],
        ['te', 'nang'],
        ['re', 'nang'],
        ['pe', 'nang'],
        ['ke', 'nang'],
        ['le', 'nang'],
        ['de', 'nang'],
        ['ge', 'nang'],
        ['be', 'nang'],
        ['ce', 'nang'],
        ['se', 'nang'],
        ['he', 'nang'],
        ['je', 'nang'],
        ['ne', 'nang'],
        ['we', 'nang'],
        ['ye', 'nang'],
        ['ze', 'nang'],
        ['a', 'ngin'],
        ['i', 'ngin'],
        ['u', 'ngin'],
        ['e', 'ngin'],
        ['o', 'ngin'],
      ],
    },
  ];
}