name: usama_quiz
description: "UsamaQuiz - Aplikasi Flutter untuk belajar aksara Jepang dengan kuis interaktif."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.5+1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Audio
  audioplayers: ^6.1.0
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  
  # Assets - Images
  assets:
    - assets/images/
    - assets/audio/
  
  # Fonts
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" 